
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np

array = np.arange(10) # 0 to 9 (0,10)
array
# 2 to 10
# array = np.arange(2, 11)
# array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
# reshape
# 3x3

array = np.arange(1,10)
#array

reshaped_array = array.reshape((3,3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [5]:
array_element = reshaped_array[1,1]
array_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

Addition = array1 + array2

substraction = array1 - array2

multliplication = array1 * array2

Division = array1 / array2

print("Addition:", Addition)
print("substraction:", substraction)
print()

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [10]:
array = np.array([1, 2, 3, 4, 5])

array_sum = array.sum()
array_mean = array.mean()
array_std = array.std()

print("sum:", array_sum,  "Mean:", array_mean,  "std:", array_std)

sum: 15 Mean: 3.0 std: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [19]:
array = np.array([1,2,3,4,5,6])

array1 = array.reshape(2,3)

array1

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [12]:
random_array = np.random.randint(50,100, size=(5,5))
random_array

array([[94, 90, 70, 61, 52],
       [67, 70, 65, 71, 73],
       [91, 58, 52, 68, 83],
       [77, 84, 85, 76, 75],
       [54, 78, 95, 76, 78]])

Replace all values in the sub-array with a specific value.


In [15]:
random_array[1:4,:] = 10
random_array

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [17]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
arr
arr[[1,3],:]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [34]:
array = np.array([0,1,2])
array

# tile

new_array = np.tile(array, (3,1))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [35]:
array_1d = np.array([0, 1, 2])
array_1d + new_array

array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [24]:
random_array1 = np.random.randint(1,100, size = (3,3))
random_array1

array([[14, 37, 47],
       [64, 95, 91],
       [ 2, 10, 91]])

In [25]:
random_array2 =np.random.randint(1,100, size = (3,3))
random_array2

array([[87, 87, 80],
       [36,  2, 77],
       [65,  1, 25]])

In [26]:
#hstack 

concatenated_horizontally = np.hstack((random_array1,random_array2))
concatenated_horizontally


array([[14, 37, 47, 87, 87, 80],
       [64, 95, 91, 36,  2, 77],
       [ 2, 10, 91, 65,  1, 25]])

In [27]:
# vstack

concatenated_vertically = np.vstack((random_array1,random_array2))
concatenated_vertically


array([[14, 37, 47],
       [64, 95, 91],
       [ 2, 10, 91],
       [87, 87, 80],
       [36,  2, 77],
       [65,  1, 25]])

In [28]:
# hsplit # vsplit

splitted_array = np.hsplit(concatenated_horizontally,2)
splitted_array

[array([[14, 37, 47],
        [64, 95, 91],
        [ 2, 10, 91]]),
 array([[87, 87, 80],
        [36,  2, 77],
        [65,  1, 25]])]

In [30]:
splitted_array = np.vsplit(concatenated_vertically,2)
splitted_array

[array([[14, 37, 47],
        [64, 95, 91],
        [ 2, 10, 91]]),
 array([[87, 87, 80],
        [36,  2, 77],
        [65,  1, 25]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [31]:
array = np.array ([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])

count_dict = {}

for i in array:
    if i in count_dict:
        count_dict[i] +=1
    else:
        count_dict[i] = 1
        
count_dict

{1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}

In [33]:
mode = None
max_count = 0

for key , value in count_dict.items():
    if value > max_count:
        max_count = value
        mod = key
        
print("mod",mod, ":" ,max_count)

mod 1 : 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

